require:
  - rubocop-rails
  - rubocop-rspec
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: true
Gemspec/RequireMFA: # new in 1.23
  Enabled: true
Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true
Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: true
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true
Lint/AmbiguousRange: # new in 1.19
  Enabled: true
Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true
Lint/DeprecatedConstants: # new in 1.8
  Enabled: true
Lint/DuplicateBranch: # new in 1.3
  Enabled: true
Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: true
Lint/EmptyBlock: # new in 1.1
  Enabled: true
Lint/EmptyClass: # new in 1.3
  Enabled: true
Lint/EmptyInPattern: # new in 1.16
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true
Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true
Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: true
Lint/RefinementImportMethods: # new in 1.27
  Enabled: true
Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true
Lint/SymbolConversion: # new in 1.9
  Enabled: true
Lint/ToEnumArguments: # new in 1.1
  Enabled: true
Lint/TripleQuotes: # new in 1.9
  Enabled: true
Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: true
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true
Naming/BlockForwarding: # new in 1.24
  Enabled: true
Security/CompoundHash: # new in 1.28
  Enabled: true
Security/IoMethods: # new in 1.22
  Enabled: true
Style/ArgumentsForwarding: # new in 1.1
  Enabled: true
Style/CollectionCompact: # new in 1.2
  Enabled: true
Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: true
Style/EmptyHeredoc: # new in 1.32
  Enabled: true
Style/EndlessMethod: # new in 1.8
  Enabled: true
Style/EnvHome: # new in 1.29
  Enabled: true
Style/FetchEnvVar: # new in 1.28
  Enabled: true
Style/FileRead: # new in 1.24
  Enabled: true
Style/FileWrite: # new in 1.24
  Enabled: true
Style/HashConversion: # new in 1.10
  Enabled: true
Style/HashExcept: # new in 1.7
  Enabled: true
Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: true

# Cops below this line have not been evaluated yet
Style/InPatternThen: # new in 1.16
  Enabled: false
Style/MagicCommentFormat: # new in 1.35
  Enabled: false
Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: false
Style/MapToHash: # new in 1.24
  Enabled: false
Style/MultilineInPatternThen: # new in 1.16
  Enabled: false
Style/NegatedIfElseCondition: # new in 1.2
  Enabled: false
Style/NestedFileDirname: # new in 1.26
  Enabled: false
Style/NilLambda: # new in 1.3
  Enabled: false
Style/NumberedParameters: # new in 1.22
  Enabled: false
Style/NumberedParametersLimit: # new in 1.22
  Enabled: false
Style/ObjectThen: # new in 1.28
  Enabled: false
Style/OpenStructUse: # new in 1.23
  Enabled: false
Style/OperatorMethodCall: # new in 1.37
  Enabled: false
Style/QuotedSymbols: # new in 1.16
  Enabled: false
Style/RedundantArgument: # new in 1.4
  Enabled: false
Style/RedundantEach: # new in 1.38
  Enabled: false
Style/RedundantInitialize: # new in 1.27
  Enabled: false
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: false
Style/RedundantStringEscape: # new in 1.37
  Enabled: false
Style/SelectByRegexp: # new in 1.22
  Enabled: false
Style/StringChars: # new in 1.12
  Enabled: false
Style/SwapValues: # new in 1.1
  Enabled: false
Rails/ActionControllerFlashBeforeRender: # new in 2.16
  Enabled: false
Rails/ActionControllerTestCase: # new in 2.14
  Enabled: false
Rails/ActionOrder: # new in 2.17
  Enabled: false
Rails/ActiveRecordCallbacksOrder: # new in 2.7
  Enabled: false
Rails/ActiveSupportOnLoad: # new in 2.16
  Enabled: false
Rails/AddColumnIndex: # new in 2.11
  Enabled: false
Rails/AfterCommitOverride: # new in 2.8
  Enabled: false
Rails/AttributeDefaultBlockValue: # new in 2.9
  Enabled: false
Rails/CompactBlank: # new in 2.13
  Enabled: false
Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: false
Rails/DotSeparatedKeys: # new in 2.15
  Enabled: false
Rails/DuplicateAssociation: # new in 2.14
  Enabled: false
Rails/DuplicateScope: # new in 2.14
  Enabled: false
Rails/DurationArithmetic: # new in 2.13
  Enabled: false
Rails/EagerEvaluationLogMessage: # new in 2.11
  Enabled: false
Rails/ExpandedDateRange: # new in 2.11
  Enabled: false
Rails/FindById: # new in 2.7
  Enabled: false
Rails/FreezeTime: # new in 2.16
  Enabled: false
Rails/I18nLazyLookup: # new in 2.14
  Enabled: false
Rails/I18nLocaleAssignment: # new in 2.11
  Enabled: false
Rails/I18nLocaleTexts: # new in 2.14
  Enabled: false
Rails/IgnoredColumnsAssignment: # new in 2.17
  Enabled: false
Rails/Inquiry: # new in 2.7
  Enabled: false
Rails/MailerName: # new in 2.7
  Enabled: false
Rails/MatchRoute: # new in 2.7
  Enabled: false
Rails/MigrationClassName: # new in 2.14
  Enabled: false
Rails/NegateInclude: # new in 2.7
  Enabled: false
Rails/Pluck: # new in 2.7
  Enabled: false
Rails/PluckInWhere: # new in 2.7
  Enabled: false
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: false
Rails/RedundantTravelBack: # new in 2.12
  Enabled: false
Rails/RenderInline: # new in 2.7
  Enabled: false
Rails/RenderPlainText: # new in 2.7
  Enabled: false
Rails/RootJoinChain: # new in 2.13
  Enabled: false
Rails/RootPathnameMethods: # new in 2.16
  Enabled: false
Rails/RootPublicPath: # new in 2.15
  Enabled: false
Rails/ShortI18n: # new in 2.7
  Enabled: false
Rails/SquishedSQLHeredocs: # new in 2.8
  Enabled: false
Rails/StripHeredoc: # new in 2.15
  Enabled: false
Rails/TimeZoneAssignment: # new in 2.10
  Enabled: false
Rails/ToFormattedS: # new in 2.15
  Enabled: false
Rails/ToSWithArgument: # new in 2.16
  Enabled: false
Rails/TopLevelHashWithIndifferentAccess: # new in 2.16
  Enabled: false
Rails/TransactionExitStatement: # new in 2.14
  Enabled: false
Rails/UnusedIgnoredColumns: # new in 2.11
  Enabled: false
Rails/WhereEquals: # new in 2.9
  Enabled: false
Rails/WhereExists: # new in 2.7
  Enabled: false
Rails/WhereMissing: # new in 2.16
  Enabled: false
Rails/WhereNot: # new in 2.8
  Enabled: false
Rails/WhereNotWithMultipleConditions: # new in 2.17
  Enabled: false
RSpec/BeEq: # new in 2.9.0
  Enabled: false
RSpec/BeNil: # new in 2.9.0
  Enabled: false
RSpec/ChangeByZero: # new in 2.11
  Enabled: false
RSpec/ClassCheck: # new in 2.13
  Enabled: false
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: false
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: false
RSpec/NoExpectationExample: # new in 2.13
  Enabled: false
RSpec/SortMetadata: # new in 2.14
  Enabled: false
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: false
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: false
RSpec/Capybara/NegationMatcher: # new in 2.14
  Enabled: false
RSpec/Capybara/SpecificActions: # new in 2.14
  Enabled: false
RSpec/Capybara/SpecificFinders: # new in 2.13
  Enabled: false
RSpec/Capybara/SpecificMatcher: # new in 2.12
  Enabled: false
RSpec/FactoryBot/ConsistentParenthesesStyle: # new in 2.14
  Enabled: false
RSpec/FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: false
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: false
RSpec/Rails/HaveHttpStatus: # new in 2.12
  Enabled: false
RSpec/Rails/InferredSpecType: # new in 2.14
  Enabled: false